# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('app\\templates', 'templates'),
        ('app\\static', 'static'),
    ],
    hiddenimports=[
        'app',
        'app.app',
        'app.database',
        'app.routes',
        'app.routes.customer_routes',
        'app.routes.work_report_routes',
        'app.routes.invoice_routes',
        'app.domain',
        'app.domain.customer',
        'app.domain.employee',
        'app.domain.employee_rate',
        'app.domain.exceptions',
        'app.domain.invoice',
        'app.domain.person',
        'app.domain.position',
        'app.domain.validations',
        'app.domain.value_objects',
        'app.domain.work_report',
        'app.model',
        'app.model.customer_mapping',
        'app.model.employee_mapping',
        'app.model.invoice_mapping',
        'app.model.position_mapping',
        'app.model.work_report_mapping',
        'app.repositories',
        'app.repositories.base',
        'app.repositories.customer_repository',
        'app.repositories.employee_repository',
        'app.repositories.invoice_repository',
        'app.repositories.work_report_repository',
        'app.service',
        'app.service.customer_service',
        'app.service.employee_service',
        'app.service.invoice_service',
        'app.service.work_report_service',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.sql.default_comparator',
        'sqlalchemy.ext.declarative',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Billing App',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
