from decimal import Decimal
# choose appropriate values for all!
# should we use something like structs to combine constants that belong together?

# Customer/employee (person) attributes
MAX_FIRST_NAME_LENGTH = 30
MAX_LAST_NAME_LENGTH = 30
MAX_NAME_LENGTH = 30
MAX_ROLE_LENGTH = 20

MAX_STREET_NAME_LENGTH = 30
MAX_STREET_NUMBER_LENGTH = 10
MAX_POSTAL_CODE_LENGTH = 10
MAX_CITY_LENGTH = 30
MAX_COUNTRY_LENGTH = 30
MAX_PHONE_NUMBER_LENGTH = 30
MAX_EMAIL_ADDRESS_LENGTH = 30

MAX_CUSTOMER_NOTES_LENGTH = 200

# Work report attributes
MAX_WORK_REPORT_TITLE_LENGTH = 100
MAX_WORK_REPORT_DESCRIPTION_LENGTH = 500
MAX_WORK_REPORT_NOTES_LENGTH = 500

# Invoice attributes
MAX_INVOICE_TITLE_LENGTH = 20
MAX_INVOICE_DESCRIPTION_LENGTH = 200
MAX_INVOICE_NOTES_LENGTH = 200

TAX_RATE = Decimal("1.081")